Catkin-ProjectName: genlisp
Version: 0.1.1
Description: ROS message generators for Lisp
Author: Bhaskara Marthi <bhaskara@willowgarage.com>
Maintainer: Bhaskara Marthi <bhaskara@willowgarage.com>
Homepage: http://www.ros.org

Depends: catkin, genmsg

Catkin-CopyrightType:  willowgarage
Catkin-DebRulesType: python_distutils
Catkin-ROS-Message-Generator: lisp
