Catkin-ProjectName: genlisp
Description: ROS message generation for Lisp
Author: Morten Kjaergaard <mkjargaard@willowgarage.com>
Maintainer:
Homepage: http://www.ros.org

Depends: catkin, genmsg

Version: 0.0.0

Catkin-CopyrightType:  willowgarage
Catkin-DebRulesType: python_distutils
Catkin-ROS-Message-Generator: lisp

